name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message),'#skip')}}
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: agile-escarpment-20043
          heroku_email: aapo.leppanen@gmail.com
          healthcheck: "https://agile-escarpment-20043.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
  taggin_pipleline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message),'#skip')}}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: commits
      #   env:
      #     COMMITS: ${{ toJson(github.event.commits) }}
      #   run: echo "$COMMITS"
      # - name: commit messages
      #   env:
      #     COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
      #   run: echo "$COMMIT_MESSAGES"
      # - name: check message
      #   env:
      #     COMMIT_MESSAGES: ${{ !contains(join(github.event.commits.*.message),'#skip') }}
      #   run: echo "$COMMIT_MESSAGES"
      # - name: more messages
      #   env:
      #     COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
      #   run: echo "$COMMIT_MESSAGES"
  notification_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Failed Deployment
      uses: 8398a7/action-slack@v3
      if: ${{ failure() }}
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    - name: Succesfull Deployment
      uses: 8398a7/action-slack@v3
      if: ${{ success() }}
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              color: 'good,
              text: `a new version has been deployed to https://agile-escarpment-20043.herokuapp.com (${process.env.AS_COMMIT}) of by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

